#!/usr/bin/env python3
"""Generate frontend/src/lib/bangladeshMap.ts from Bangladesh's official division boundaries.

Source: geoBoundaries (open data, CC BY 4.0), BGD ADM1 simplified:
https://github.com/wmgeolab/geoBoundaries/raw/main/releaseData/gbOpen/BGD/ADM1/geoBoundaries-BGD-ADM1_simplified.geojson

Technique: equirectangular projection with a cos(latitude) correction (accurate enough at this scale), then
Douglas-Peucker simplification in screen space so the SVG stays small. Run: python3 scripts/gen_bangladesh_map.py
"""

from __future__ import annotations

import json
import math
import urllib.request
from pathlib import Path

URL = ("https://github.com/wmgeolab/geoBoundaries/raw/main/releaseData/gbOpen/BGD/ADM1/"
       "geoBoundaries-BGD-ADM1_simplified.geojson")
OUT = Path(__file__).resolve().parent.parent / "frontend" / "src" / "lib" / "bangladeshMap.ts"
NAMES = {"Chittagong": "Chattogram", "Rajshani": "Rajshahi", "Barisal": "Barishal"}

# Two views: the whole country (overview) and the Dhaka-Chattogram corridor where the network lives (detail).
VIEWS = {
    "overview": {"lon": (88.0, 92.7), "lat": (20.6, 26.65), "k": 58.0, "x": 16.0, "y": 44.0, "tol": 0.6},
    "detail": {"lon": (89.75, 92.45), "lat": (21.15, 24.45), "k": 160.0, "x": 300.0, "y": 16.0, "tol": 0.45},
}


def projector(v: dict) -> tuple:
    (lon0, lon1), (lat0, lat1) = v["lon"], v["lat"]
    c = math.cos(math.radians((lat0 + lat1) / 2))
    k = v["k"]
    width, height = (lon1 - lon0) * c * k, (lat1 - lat0) * k

    def p(lon: float, lat: float) -> tuple[float, float]:
        return v["x"] + (lon - lon0) * c * k, v["y"] + (lat1 - lat) * k

    return p, width, height, c


def dp(points: list[tuple[float, float]], tol: float) -> list[tuple[float, float]]:
    """Douglas-Peucker line simplification."""
    if len(points) < 3:
        return points
    (x1, y1), (x2, y2) = points[0], points[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy)
    best, idx = 0.0, 0
    for i in range(1, len(points) - 1):
        x0, y0 = points[i]
        # Closed rings start and end on the same point: fall back to plain distance from it.
        d = abs(dy * x0 - dx * y0 + x2 * y1 - y2 * x1) / norm if norm > 1e-9 else math.hypot(x0 - x1, y0 - y1)
        if d > best:
            best, idx = d, i
    if best <= tol:
        return [points[0], points[-1]]
    return dp(points[: idx + 1], tol)[:-1] + dp(points[idx:], tol)


def path(geom: dict, proj, tol: float) -> str:
    polys = geom["coordinates"] if geom["type"] == "MultiPolygon" else [geom["coordinates"]]
    parts = []
    for poly in polys:
        for ring in poly:
            pts = dp([proj(lon, lat) for lon, lat in ring], tol)
            if len(pts) < 3:
                continue
            parts.append("M" + "L".join(f"{x:.1f},{y:.1f}" for x, y in pts) + "Z")
    return "".join(parts)


def main() -> None:
    with urllib.request.urlopen(URL, timeout=60) as resp:
        data = json.load(resp)
    lines = [
        "// Generated by scripts/gen_bangladesh_map.py from geoBoundaries BGD ADM1 (CC BY 4.0). Do not edit by hand.",
        "export interface MapView { x: number; y: number; width: number; height: number; lon0: number; lat1: number;"
        " k: number; cosLat: number; divisions: { name: string; d: string }[] }",
        "",
    ]
    for name, v in VIEWS.items():
        proj, w, h, c = projector(v)
        divisions = []
        for f in data["features"]:
            raw = f["properties"]["shapeName"]
            divisions.append({"name": NAMES.get(raw, raw), "d": path(f["geometry"], proj, v["tol"])})
        view = {"x": v["x"], "y": v["y"], "width": round(w, 1), "height": round(h, 1), "lon0": v["lon"][0],
                "lat1": v["lat"][1], "k": v["k"], "cosLat": round(c, 6), "divisions": divisions}
        lines.append(f"export const {name.upper()}: MapView = {json.dumps(view)}")
        lines.append("")
    lines.append("/** Project a longitude/latitude into a view's SVG coordinates. */")
    lines.append("export function project(v: MapView, lon: number, lat: number): [number, number] {")
    lines.append("  return [v.x + (lon - v.lon0) * v.cosLat * v.k, v.y + (v.lat1 - lat) * v.k]")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
